export const CLICK_HAMBURGER = 'CLICK_HAMBURGER'
export const CLICK_NAV_CLOSE = 'CLICK_NAV_CLOSE'
export const CLICK_NAV_LOCATION_FOLDER = 'CLICK_NAV_LOCATION_FOLDER'
export const CLICK_NAV_KTOWN1ST_FOLDER = 'CLICK_NAV_KTOWN1ST_FOLDER'
export const CLICK_HEADER_SECTION = "CLICK_HEADER_SECTION"
export const CLICK_BTN_MORE = "CLICK_BTN_MORE"
export const CLICK_MAIN_LOGO = "CLICK_MAIN_LOGO"
export const CLICK_NAV_LIVING_INFO = "CLICK_NAV_LIVING_INFO"
export const ClICK_SEARCH_BTN = "ClICK_SEARCH_BTN"
export const CHANGE_HEADER_GNB = "CHANGE_HEADER_GNB"


export const PETCHING_MAIN_TOP_NEWS = "PETCHING_MAIN_TOP_NEWS"
export const PETCHING_MAIN_NEWS_LIST = "PETCHING_MAIN_NEWS_LIST"
export const PETCHING_TOP50 = "PETCHING_TOP50"
export const PETCHING_SECTION_OPINION = "PETCHING_SECTION_OPINION"
export const PETCHING_PHOTO_NEWS = "PETCHING_PHOTO_NEWS"
export const PETCHING_MAIN_OPINION = "PETCHING_MAIN_OPINION"
export const PETCHING_ARTICLE_DETAIL = "PETCHING_ARTICLE_DETAIL"
export const PETCHING_ARTICLE_DETAIL_BESTCLICK = "PETCHING_ARTICLE_DETAIL_BESTCLICK"

export const PETCHING_SECTION_ARTICLE_LIST = "PETCHING_SECTION_ARTICLE_LIST"
export const CHANGE_BRANCH = "CHANGE_BRANCH"
export const PETCHING_DAILY_FORTUNE = "PETCHING_DAILY_FORTUNE"


export const PETCHING_ARTICLE_COMMENT = "PETCHING_ARTICLE_COMMENT"
